#!/usr/bin/bash

set -e

prefix=$(cat prefix)

appdir="${prefix}/share/applications"
olddesktop="${appdir}/atom.desktop"
newdesktop="${appdir}/io.atom.Atom.desktop"
sed -i -e 's/Icon=.*/Icon=io.atom.Atom/' "${olddesktop}"
mv "${olddesktop}" "${newdesktop}"
install -D 'io.atom.Atom.appdata.xml' "${prefix}/share/appdata/io.atom.Atom.appdata.xml"
